{% set data= load_setup_py_data() %}
package:
  name: ts-atmcs
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  string: "py{{ PY_VER | replace('.', '') }}{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"
  entry_points:
    - run_atmcs = lsst.ts.atmcs:run_atmcs

test:
  requires:
    - ts-conda-build =0.5
    - ts-xml {{ xml_version }}
    - ts-salobj {{ salobj_version }}
    - ts-attcpip
    - ts-simactuators
    - ts-tcpip >=1.1.1
    - ts-utils
  source_files:
    - bin
    - pyproject.toml
    - python
    - tests
  commands:
    - pytest

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools
    - setuptools_scm
  build:
    - python {{ python }}
    - setuptools
    - setuptools_scm
  run:
    - python {{ python }}
    - ts-xml
    - ts-salobj
    - ts-attcpip
    - ts-simactuators
    - ts-tcpip >=1.1.1
    - ts-utils
